# Nixkell config

ghc = "8.10.4"

[env]
tools = [
  "cabal-install",
  "haskell-language-server",
  "haskellPackages.implicit-hie",
  "hlint",
  "niv",
  "nixpkgs-fmt",
  "ormolu",
]

[ignore]
files = [
  "README.md",
]
paths = [
  ".github",
  ".vscode",
]
